variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

stages:
  - test

.template: &TEMPLATE
    stage: test
    before_script:
        - pip3 install codecov pytest-cov pylint
        - pip3 install --upgrade setuptools
        - export PYTHONPATH=$PYTHONPATH:${CI_PROJECT_DIR}/pypact
    script:
        - cd ${CI_PROJECT_DIR}
        - pip3 install .
        - python3 setup.py test
        - coverage run tests/testsuite.py
        - pylint -j4 filecompare --rcfile=${CI_PROJECT_DIR}/.pylintrc || true
    tags:
        - ubuntu

ubuntu16.04:
    <<: *TEMPLATE
    image: fispact/ubuntu:16.04_gfortran_7

centos6.9:
    <<: *TEMPLATE
    image: fispact/centos:6.9_gfortran_6

debian9.7:
    <<: *TEMPLATE
    image: fispact/debian:9_gfortran_7_data
